#!/bin/bash
#
# Add new domains to your setup. This creates the website folder, link to the
# /etc/hosts file, creates a SSL certificate and sets up a git project for you
# to begin using.
# 
# Copyright: Copyright (C) 2018 Justin Hartman (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.5.1
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.1.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

#######################################
# Includes the colour palette and
# other global variables
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Variables
#######################################
global_includes ()
{
    source scripts/globals.sh
    source scripts/colour_palette.sh
}

#######################################
# This is the main application thread.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   String Multi-interactive messages.
#######################################
main_application ()
{
    # shellcheck source=scripts/enter_domain.sh
    source $scripts/enter_domain.sh # Get domain name to be added
    # shellcheck source=scripts/openssl_config.sh
    source $scripts/openssl_config.sh # Add domain to 'openssl.conf' configuration file
    # shellcheck source=scripts/openssl_command.sh
    source $scripts/openssl_command.sh # Create SSL Certificates for the new domain
    # shellcheck source=scripts/keychain_certificate.sh
    source $scripts/keychain_certificate.sh # Adding new SSL cert to macOS' Keychain
    # shellcheck source=scripts/hosts_domain.sh
    source $scripts/hosts_domain.sh # Add new domain to hosts file
    # shellcheck source=scripts/folder_and_git.sh
    source $scripts/folder_and_git.sh # Add website folder and initialise git repo
    # shellcheck source=scripts/git_setup.sh
    source $scripts/git_setup.sh # git initial structure, files and check-in
    # shellcheck source=scripts/folder_permissions.sh
    source $scripts/folder_permissions.sh # Setting correct folder permissions

    echo "" >&2
    echo -e "${RED} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Congratulations! Your domain has been added |" >&2
    echo "|  and you can begin using it immediately.     |" >&2
    echo "|  You will find your website folder in the    |" >&2
    echo "|  dist/websites/ folder and you can edit      |" >&2
    echo "|  all your files here. You can access your    |" >&2
    echo "|  website by visiting the following URL:      |" >&2
    echo "|  https://${domain}                            " >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\\n" >&2
}

global_includes # Includes global variables and file paths.

if ! [ "$(id -u)" = 0 ]; then
    echo "" >&2
    echo -e "${RED} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "| This needs to be run as root. Please run it  |" >&2
    echo "| again using sudo, as per the command below:  |" >&2
    echo -e "| ${NOC}${GRY}$ ${NOC}${BLU}sudo ./add_domains                         ${NOC}${RED}|" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\\n" >&2
    exit 1
fi

main_application # Runs the main install
exit 0
