#!/bin/bash
#
# Upgrade all the software.
#
# Copyright: Copyright 2018-2020 Justin Hartman (https://justinhartman.co)
# Author   : Justin Hartman <code@justinhartman.co> (https://justinhartman.co)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 1.2.2
# Link     : https://github.com/justinhartman/lamp-ssl
# Since    : 1.1.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

#######################################
# Includes the colour palette and
# other global variables
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Variables
#######################################
global_includes() {
    source ./scripts/globals.sh
    source ./scripts/colour_palette.sh
}

#######################################
# This is the main application thread.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   String Multi-interactive messages.
#######################################
main_application() {
    # shellcheck source=scripts/upgrade_software.sh
    source "${scripts}"/upgrade_software.sh # Run upgrade script.
    printf "${GRN}%s\\n" "$TOP"
    printf '* %-76s %s\n' "Congratulations! You have successfully upgraded all the software." "*"
    printf "%s${NOC}\\n\\n" "$BOTTOM"
}

global_includes # Includes global variables and file paths.

if ! [ "$(id -u)" = 0 ]; then
    printf "${RED}%s\\n" "$TOP"
    printf '* %-76s %s\n' "This needs to be run as root. Please run it again using 'sudo' by executing" "*"
    printf '* %-76s %s\n' "the following command: $ sudo ./lamp-upgrade" "*"
    printf "%s${NOC}\\n\\n" "$BOTTOM"

    exit 1
fi

#######################################
# Runs the main upgrade.
#######################################
main_application

exit 0
