#!/bin/bash
#
# Sets up the self-signed SSL certificates for Apache 2 and adds them as
# trusted certificates to Apple's Keychain.
# 
# Copyright: Copyright (C) 2018 Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.4.1
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.1.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 
# From https://github.com/thojansen/client-certificates/blob/master/ssl/setup.sh
# 

# Sets the directory to install the SSL certs.
dir="/usr/local/var/www/ssl-test"

setup_ssl ()
{
    echo "" >&2
    echo -e "${BRO} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Setting up the self-signed SSL certificates |" >&2
    echo "|  for Apache 2 and adding them to Apple's     |" >&2
    echo "|  Keychain as trusted SSL certificates.       |" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2

    # Create the SSL directory.
    mkdir -p /usr/local/var/www/ssl-test
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully created the ssl directory.${NOC}\n\n"

    # Copy the `src/ssl/openssl.conf` to $dir.
    cp src/ssl/openssl.conf $dir/

    # create rootCA certificate
    openssl genrsa -out $dir/localhost_rootCA.key 2048
    openssl req -x509 -new -nodes \
        -key $dir/localhost_rootCA.key \
        -days 10950 \
        -out $dir/localhost_rootCA.crt \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=22 Digital Root CA"
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully created the rootCA SSL.${NOC}\n\n"

    # create server key and certificate
    openssl genrsa -out $dir/localhost_server.key 2048
    openssl req -new \
        -key $dir/localhost_server.key \
        -out $dir/localhost_server.csr \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=localhost"
    openssl x509 -req \
        -in $dir/localhost_server.csr \
        -CA $dir/localhost_rootCA.crt \
        -CAkey $dir/localhost_rootCA.key \
        -CAcreateserial \
        -out $dir/localhost_server.crt \
        -days 9125 \
        -sha256 \
        -extfile $dir/openssl.conf
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully created the localhost SSL.${NOC}\n\n"

    # create client key and certificate
    openssl genrsa -out $dir/localhost_client.key 2048
    openssl req -new -nodes \
        -key $dir/localhost_client.key \
        -out $dir/localhost_client.csr \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=Client Certificate"
    openssl x509 -req -in $dir/localhost_client.csr -CA $dir/localhost_rootCA.crt \
        -CAkey $dir/localhost_rootCA.key -CAcreateserial -out $dir/localhost_client.crt \
        -days 9125
    openssl pkcs12 -export -inkey $dir/localhost_client.key -in $dir/localhost_client.crt \
        -name $dir/localhost_client -out $dir/localhost_client.p12
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully created the client SSL.${NOC}\n\n"

    # Create symlink to the SSL folder in dist.
    ln -s $dir dist/ssl
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Created a symbolic link from '$dir' to 'dist/ssl'.${NOC}\n\n"
}

addto_keychain ()
{
    echo "" >&2
    echo -e "${BRO} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Adding certificates to Apple's Keychain as  |" >&2
    echo "|  trusted SSL certificates.                   |" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
    security add-trusted-cert -d -r trustRoot \
    -p ssl \
    -k '/Library/Keychains/System.keychain' \
    $dir/localhost_server.crt
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully updated the macOS
  Keychain with a new SSL certificate with ${domain} added.${NOC}\n"
}

setup_ssl
addto_keychain
