#!/bin/bash
#
# Fully automated LAMP installation and configuration using Trusted localhost SSL Certificates
# 
# Copyright: Copyright (C) 2018 Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.2.2
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.1.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 
# From https://github.com/thojansen/client-certificates/blob/master/ssl/setup.sh
# 

cd ssl/ # get in the right directory
# create rootCA certificate
openssl genrsa -out localhost_rootCA.key 2048
openssl req -x509 -new -nodes \
        -key localhost_rootCA.key \
        -days 10950 \
        -out localhost_rootCA.crt \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=22 Digital Root CA"
# create server key and certificate
openssl genrsa -out localhost_server.key 2048
openssl req -new \
        -key localhost_server.key \
        -out localhost_server.csr \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=localhost"
openssl x509 -req \
        -in localhost_server.csr \
        -CA localhost_rootCA.crt \
        -CAkey localhost_rootCA.key \
        -CAcreateserial \
        -out localhost_server.crt \
        -days 9125 \
        -sha256 \
        -extfile "openssl.conf"
# create client key and certificate
openssl genrsa -out localhost_client.key 2048
openssl req -new \
        -key localhost_client.key \
        -out localhost_client.csr \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=Client Certificate"
openssl x509 -req -in localhost_client.csr -CA localhost_rootCA.crt \
        -CAkey localhost_rootCA.key -CAcreateserial -out localhost_client.crt \
        -days 9125
openssl pkcs12 -export -inkey localhost_client.key -in localhost_client.crt \
        -name localhost_client -out localhost_client.p12
