#!/bin/bash
# From https://github.com/thojansen/client-certificates/blob/master/ssl/setup.sh
cd ssl/
# create rootCA certificate
openssl genrsa -out localhost_rootCA.key 2048
openssl req -x509 -new -nodes \
        -key localhost_rootCA.key \
        -days 10950 \
        -out localhost_rootCA.crt \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=22 Digital Root CA"
# create server key and certificate
openssl genrsa -out localhost_server.key 2048
openssl req -new \
        -key localhost_server.key \
        -out localhost_server.csr \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=localhost"
openssl x509 -req \
        -in localhost_server.csr \
        -CA localhost_rootCA.crt \
        -CAkey localhost_rootCA.key \
        -CAcreateserial \
        -out localhost_server.crt \
        -days 9125 \
        -sha256 \
        -extfile "openssl.conf"
# create client key and certificate
openssl genrsa -out localhost_client.key 2048
openssl req -new \
        -key localhost_client.key \
        -out localhost_client.csr \
        -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=22 Digital/OU=Security/CN=Client Certificate"
openssl x509 -req -in localhost_client.csr -CA localhost_rootCA.crt \
        -CAkey localhost_rootCA.key -CAcreateserial -out localhost_client.crt \
        -days 9125
openssl pkcs12 -export -inkey localhost_client.key -in localhost_client.crt \
        -name localhost_client -out localhost_client.p12
