#!/bin/bash
#
# The main install script that sets up and installs everything required
# by the application.
# 
# Copyright: Copyright (C) 2018 Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.4.1
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.4.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

#######################################
# Includes the colour palette and
# other global variables
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Variables
#######################################
global_includes ()
{
    source scripts/globals.sh
    source scripts/colour_palette.sh
}

#######################################
# This installs Homebrew (`brew`) but
# only if the user hasn't got it and
# wants to install it via the script.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Void
#######################################
brew_install ()
{
    echo "" >&2
    echo -e "${RED} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Installing Homebrew.                        |" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
    echo "" >&2
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully installed Homebrew.${NOC}\n"
}

#######################################
# Installs the packages required from
# `brew` running `brew install`.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Void
#######################################
brew_packages ()
{
    echo "" >&2
    echo -e "${RED} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Installing Apache 2 and PHP.                |" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
    brew install php httpd mysql
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully installed Apache 2
  and PHP.${NOC}\n"
}

#######################################
# This is the main application thread.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   String Multi-interactive messages.
#######################################
main_application ()
{
    # source $scripts/brew_install.sh # Install Homebrew and packages
    brew_install
    brew_packages
    source $scripts/ssl_install.sh # Setup self-signed SSL
    source $scripts/apache_config.sh # Configure Apache 2
    source $scripts/folder_permissions.sh # Setting correct folder permissions

    echo "" >&2
    echo -e "${RED} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Congratulations! You have successfully      |" >&2
    echo "|  setup your localhost configuration.         |" >&2
    echo "|  All the files you may need to edit are      |" >&2
    echo "|  contained in the `/dist/` folder. This      |" >&2
    echo "|  includes any website you add and access to  |" >&2
    echo "|  the ssl, adminer, phpmyadmin, error-pages   |" >&2
    echo "|  and hosts folder.                           |" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
}

global_includes # Includes global variables and file paths.

if ! [ $(id -u) = 0 ]; then
    echo "" >&2
    echo -e "${RED} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "| This needs to be run as root. Please run it  |" >&2
    echo "| again using sudo, as per the command below:  |" >&2
    echo -e "| ${NOC}${GRY}$ ${NOC}${BLU}sudo ./install                             ${NOC}${RED}|" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
    exit 1
fi

main_application # Runs the main install
exit 0
