#!/bin/bash
#
# Apache 2.4 Setup and Configuration
# 
# Copyright: Copyright (C) 2018 Justin Hartman (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.2.3
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.2.3
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

# Back up httpd.conf, httpd-ssl.conf and httpd-vhosts.conf
mv /usr/local/etc/httpd/httpd.conf /usr/local/etc/httpd/httpd.conf.bak
mv /usr/local/etc/httpd/extra/httpd-ssl.conf /usr/local/etc/httpd/extra/httpd-ssl.conf.bak
mv /usr/local/etc/httpd/extra/httpd-vhosts.conf /usr/local/etc/httpd/extra/httpd-vhosts.conf.bak

# Copy over new Apache config files.
cp ../src/httpd/conf/httpd.conf /usr/local/etc/httpd/
cp ../src/httpd/conf/httpd-ssl.conf /usr/local/etc/httpd/extra/httpd-ssl.conf
cp ../src/httpd/conf/httpd-vhosts.conf /usr/local/etc/httpd/extra/httpd-vhosts.conf

mkdir -p /usr/local/var/www/websites
