#!/bin/bash
#
# Fully automated LAMP installation and configuration using Trusted localhost 
# SSL Certificates
# 
# Copyright: Copyright (C) 2018 Justin Hartman (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.2.2
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.2.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

#######################################
# Installs the Adminer project by
# checking out the source code to a
# local `/adminer/` folder.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Void
#######################################
adminer_install ()
{
    echo "" >&2
    echo -e "${ORG} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Installing the Adminer project...           |" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
    git clone https://github.com/justinhartman/adminer-custom.git adminer
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully cloned the Adminer
  sub-module to the /adminer/ folder.${NOC}\n"
}

errorpages_install ()
{
    echo "" >&2
    echo -e "${ORG} ----------------------------------------------" >&2
    echo "|                                              |" >&2
    echo "|  Installing the Apache Error Pages project...|" >&2
    echo "|                                              |" >&2
    echo -e " ---------------------------------------------- ${NOC}\n" >&2
    git clone https://github.com/justinhartman/Apache-Error-Pages.git \
    httpd/error-pages
    printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Successfully cloned the Apache
  Error Pages sub-module to the /httpd/error-pages/ folder.${NOC}\n"
}

#######################################
# Install all the sub-modules required
# for the project.
#######################################
adminer_install
errorpages_install
printf "\n${GRN}\xE2\x9C\x94${NOC} ${CYA}Installation complete. All the
  required sub-modules have been installed.${NOC}\n"
