#!/bin/bash
#
# Fully automated LAMP installation and configuration using Trusted localhost 
# SSL Certificates
# 
# Copyright: Copyright (C) 2018 Justin Hartman (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.2.0
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.2.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

#######################################
# Installs the Adminer project by
# checking out the source code to a
# local `/adminer/` folder.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Void
#######################################
adminer_install ()
{
    echo "Installing the Adminer project..." >&2
    git clone https://github.com/justinhartman/adminer-custom.git adminer
}

errorpages_install ()
{
    echo "Installing the Apache Error Pages project..." >&2
    git clone https://github.com/justinhartman/Apache-Error-Pages.git httpd/error-pages
}

#######################################
# Install all the sub-modules required
# for the project.
#######################################
adminer_install
echo "Done. Moving on to the next project." >&2
errorpages_install
echo "Installation complete. All the required sub-modules for the project " >&2
echo "have now been installed." >&2
