#!/bin/bash
#
# Fully automated LAMP installation and configuration using Trusted localhost 
# SSL Certificates
# 
# Copyright: Copyright (C) 2018 Justin Hartman (https://justin.hartman.me)
# Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
# License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
# Version  : 0.2.0
# Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
# Link     : https://justin.hartman.me
# Since    : 0.2.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

#######################################
# This method will upgrade the core as
# well as third-party repositories to
# ensure that we are running off the
# latest code-base.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Void
#######################################
upgrade_projects ()
{
    #upgrades projects
    echo "Checking if I need to upgrade the core..." >&2
    git pull
    echo "Checking for an upgrade to the Adminer project..." >&2
    cd adminer/
    git pull
    echo "Checking for an upgrade to Apache Error Pages project..." >&2
    cd ../httpd/error-pages/
    git pull
}

#######################################
# Get users input in order to upgrade
# the core and sub-modules linked to 
# the project.
#######################################
echo "Do you want to upgrade this project and all the third-party" >&2
echo -n "software linked to it (Y/N)?" >&2
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then
    upgrade_projects
else
    echo "OK, I'm not going to upgrade any of the software." >&2
    echo "Please note, you should keep all software up to date." >&2
    echo "Using the most up to date files ensures you benefit" >&2
    echo "from bug fixes and enhancements. You should consider updating." >&2
fi
